version: '3.8'
services:
  payment-db:
    image: postgres:15
    container_name: payment-db-postgres
    environment:
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=payment_service_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
   
  message-broker:
    image: rabbitmq:3-management
    container_name: payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: payment-elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false" # Desabilita segurança para ambiente de dev
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    container_name: payment-kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200" 
    depends_on:
      - elasticsearch
volumes:
  pgdata: 
  rabbitmq_data:
  esdata: