# Kong Plugins for Payment Service
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: payment-cors
  namespace: tech-challenge-payment
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    - Authorization
    - X-Correlation-ID
  exposed_headers:
    - X-Auth-Token
    - X-Correlation-ID
  credentials: true
  max_age: 3600
  preflight_continue: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: payment-correlation-id
  namespace: tech-challenge-payment
plugin: correlation-id
config:
  header_name: X-Correlation-ID
  generator: uuid#counter
  echo_downstream: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: payment-rate-limiting
  namespace: tech-challenge-payment
plugin: rate-limiting
config:
  minute: 100
  hour: 1000
  policy: local
  fault_tolerant: true
  hide_client_headers: false