# New Relic Secrets Configuration
# This file creates a Kubernetes secret to store New Relic license key
# Replace YOUR_NEW_RELIC_LICENSE_KEY with your actual New Relic license key

apiVersion: v1
kind: Secret
metadata:
  name: newrelic-secrets
  namespace: tech-challenge-payment
type: Opaque
stringData:
  license-key: "6ec0f96b33c41f8c96ce75a4bc6c5b9eFFFFNRAL"