AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PaymentService.Processor
  Processa comandos de pagamento recebidos via SQS para os contextos de Wallet e Purchase.

Parameters:
  RdsHost:
    Type: String
    Description: O endpoint do banco de dados RDS.
  RdsPassword:
    Type: String
    Description: A senha do banco de dados RDS.
    NoEcho: true 
  SnsTopicArn:
    Type: String
    Description: O ARN do tópico SNS para publicar eventos.
  WalletQueueArn:
    Type: String
    Description: O ARN da fila SQS de comandos da carteira.
  PurchaseQueueArn:
    Type: String
    Description: O ARN da fila SQS de comandos de compra.
  ReplyQueueName:
    Type: String
    Description: O nome da fila SQS para respostas RPC.
  ElasticUrl:
    Type: String
    Description: URL do cluster Elasticsearch.
  ElasticApiKey:
    Type: String
    Description: Chave de API do Elasticsearch.
    NoEcho: true

Globals:
  Function:
    Timeout: 30 
    MemorySize: 512 

Resources:
  PaymentProcessorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: PaymentService.Processor::PaymentService.Processor.Function::FunctionHandler
      Runtime: dotnet8
      CodeUri: ./  

      Events:
        WalletQueueTrigger:
          Type: SQS
          Properties:
            Queue: !Ref WalletQueueArn 
            BatchSize: 10 
            Enabled: true

        PurchaseQueueTrigger:
          Type: SQS
          Properties:
            Queue: !Ref PurchaseQueueArn 
            BatchSize: 10
            Enabled: true
      
      Policies:
        - SQSPollerPolicy:
            QueueName: wallet-queue 
        - SQSPollerPolicy:
            QueueName: purchase-queue 
            
        - SNSPublishMessagePolicy:
            TopicName: payment-topic 
        - SQSSendMessagePolicy:
            QueueName: my-test-reply-queue 
        - VPCAccessPolicy: {}
  
      Environment:
        Variables:
          ConnectionStrings__DefaultConnection: !Sub "Host=${RdsHost};Port=5432;Database=postgres;Username=postgres;Password=${RdsPassword}"
          AWS__Region: "sa-east-1"
          AWS__SnsTopicArn: !Ref SnsTopicArn
          AWS__WalletCommandQueueUrl: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${WalletQueueArn}" 
          AWS__PurchaseCommandQueueUrl: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${PurchaseQueueArn}"
          
          Serilog__Using__0: "Serilog.Sinks.Console"
          Serilog__Using__1: "Serilog.Sinks.Elasticsearch"
          Serilog__Using__2: "Serilog.Enrichers.Environment"
          Serilog__Using__3: "Serilog.Enrichers.Thread"
          
          Serilog__MinimumLevel__Default: "Information"
          Serilog__MinimumLevel__Override__Microsoft: "Warning"

          Serilog__WriteTo__0__Name: "Console"
          Serilog__WriteTo__1__Name: "Elasticsearch"
          Serilog__WriteTo__1__Args__nodeUris: !Ref ElasticUrl
          Serilog__WriteTo__1__Args__indexFormat: "paymentservice-logs-{0:yyyy.MM.dd}"
          Serilog__WriteTo__1__Args__autoRegisterTemplate: "true"
          Serilog__WriteTo__1__Args__apiKey: !Ref ElasticApiKey

          Serilog__Enrich__0: "FromLogContext"
          Serilog__Enrich__1: "WithMachineName"
          Serilog__Enrich__2: "WithThreadId"
